### ISSUE TITLE
Input string is a not well formed JSON, expected [:] found [a] (position: 16)

### ISSUE THREAD

**Issue by phgachoud** [eiffelhub/json#16]
Trying to parse
`{ "name":"someName", "main_email":"someEmail@foo.com", "main_phone": "12345678" } `

I got a `Input string is a not well formed JSON, expected [:] found [a] (position: 4)` on postion 4 and position 16, am I wrong what I try to parse or what?

My caller is following and the l_json_parser.is_valid returns false:
```
			create l_json_parser.make_with_string (a_json_s)
			l_json_parser.parse_content
			if l_json_parser.is_valid
					and then attached l_json_parser.parsed_json_value as l_parsed_json_value then
```

after some research this doesn't seem to work
```
--	json_content: STRING = "[{%"name%": %"someValue%"}]" -- NOT WORKING
--	json_content: STRING = "{%"name%": %"someValue%"}" -- NOT WORKING
--	json_content: STRING = "[
--	{
--	name: "someName",
--	surname: "someSurName"
--	}
--	]" -- NOT WORKING
```

1) I tried more examples with your basic example and am unable to parse strings without `[` at the beginning, am I wrong or is it accepted as I read [here](https://www.json.org/).
2) When the given string is not formatted with new_lines it seems to be unable to parse. Whats the reason for that for you? 

Thx in advance for considering my ignorance on all about the JSON standards... my point was that I have the same client (angular) with java and worked like a charm, so either is the java lib too permissive or there is an adaptation needed on this lib.

**Comment by jvelilla** [comment]
Hi @phgachoud, please if you can create a little GitHub project and share your example it would be great.

I've tested your example and works fine for me,  I've just copy paste what you have posted.

```
	test
		local
			parser: JSON_PARSER
		do
					-- Create parser for content `json_content'
			create parser.make_with_string (json_content)
					-- Parse the content
			parser.parse_content
			if
				parser.is_valid and then
				attached parser.parsed_json_value as jv
			then
				if
					attached {JSON_OBJECT} jv as j_object and then
					attached {JSON_STRING} j_object.item ("name") as j_name and then
					attached {JSON_STRING} j_object.item ("main_email") as j_email and then
					attached {JSON_STRING} j_object.item ("main_phone") as j_phone 
				then
					print ("%NThe name value is: " + j_name.unescaped_string_8)
					print ("%NThe name value is: " + j_email.unescaped_string_8)
					print ("%NThe name value is: " + j_phone.unescaped_string_8)

				end

			end
		end


	json_content: STRING = "[
				{ "name":"someName", "main_email":"someEmail@foo.com", "main_phone": "12345678" }
	 ]"

```

About your examples, I don't see anything wrong, but it would help If you can share the example

```
--	json_content: STRING = "[{%"name%": %"someValue%"}]" -- NOT WORKING (1)
--	json_content: STRING = "{%"name%": %"someValue%"}" -- NOT WORKING  (2)
--	json_content: STRING = "[
--	{
--	name: "someName",
--	surname: "someSurName"
--	}
--	]" -- NOT WORKING  (3)
```` 
Question:  What does it mean NOT WORKING?
1. Does the parser return `False` and report an error?
2. Does the parser return  `True` but the result is not what you expect?

(1).  In this case the string constant is using then escaping character `%`, the parser should return a `JSON_ARRAY`. 
(2).  Similar to 1 but as you are not using `[ ]` then the result should be a `JSON_OBJECT`
(3). Here  you are using one version of[ Multine Strings](https://www.eiffel.org/doc/eiffel/ET-_Other_Mechanisms) and is not needed to do escaping, the result should be a `JSON_OBJECT`

By the way can you run the test suites, just the test `TEST_JSON_SUITE`  here we use a lot STRINGs constants with escaping.

**Comment by phgachoud** [comment]
Hi @jvelilla many thx to take the time of watching my example, I'm struggling with these objects of course doing something more complex and just went aware that the '[' character in Eiffel is done to set a string inline. So actually its finally working for me. So misunderstanding things I was trying with web service call to parse

- attributes names without '"' or unescaped
`{name:"name_20181009_023832",main_email:"email_20181009_023832",main_phone:"phone_20181009_023832"}` which is wrong and doesn't work, so my wrong deduction was that I had to:
- Prepending and append with '[' ']' the String as into the class example
`[{"name":"name_20181009_023832","main_email":"email_20181009_023832","main_phone":"phone_20181009_023832"}]` which neither does worked to get the attached `{JSON_STRING} {JSON_OBJECT}.item('field_name')`
- and then finally got it working with `{"name":"name_20181009_023832","main_email":"email_20181009_023832","main_phone":"phone_20181009_023832"}` in my project! 

Its like that that misunderstanding follow their way! Thx a lot for your patience! Hope this issue helps others too...
