### ISSUE TITLE
Void safety with json.ecf

### ISSUE THREAD

**Issue by phgachoud** [eiffelhub/json#21]
Hi,

more than an issue, was wondering that there is an `json_safe.ecf` and a `json.ecf` and the `json_safe.ecf` says that it is obsolete and the `json.ecf` has to be used. 

Is the `json.ecf` void safe even if its not declared within a <capability><void_safety support... tag into the ecf file?

**Comment by jocelyn** [comment]
With recent ecf schema  (including the http://www.eiffel.com/developers/xml/configuration-1-20-0 ), default value for void_safety capability is full void-safe, and default for concurrency capability is SCOOP .

If you open the lib within EiffelStudio you will see the value.

And the *-safe.ecf are now usually just a redirection to the *.ecf file.
Soon or later, we will remove all the -safe.ecf files, and they are useless now, thanks to the notion of capability.


So yes, json library is fully void-safe, and SCOOP capable.
