### ISSUE TITLE
SCOOP compatibilty of json.ecf

### ISSUE THREAD

**Issue by phgachoud** [eiffelhub/json#22]
Still having `A library used by the current project ... cannot be used under the selected settings`  into `json.ecf` Capability "Concurrency" of dependent target has value "None" insufficient for current target setting "SCOOP"

**Comment by jocelyn** [comment]
Which version of EiffelStudio are you using?
If you use a recent one, let's say 19.05 , the default concurrency capability is SCOOP (according to the ecf schema version).
And I made the change to use recent ecf schema.

So you may use a old version of EiffelStudio, or may not have the latest source code for json

**Comment by phgachoud** [comment]
Many thx for your details, I'm using 19.10 enterprise. I'll check more in details! now understood perfectly.
